# Custom Language File for Launcher Customizer

[ejs.app]
title = "Muspelheim Launcher"

[ejs.landing]
mediaGitHubURL = "https://store.muspelheim.world/"
mediaTwitterURL = "https://x.com/MuspelheimMC"
mediaInstagramURL = "http://94.23.44.138:8100/"
mediaYouTubeURL = "https://www.youtube.com/@tyrthurey"
mediaDiscordURL = "https://discord.gg/h8cRxgYX44"

[ejs.settings]
sourceGithubLink = "https://github.com/Tyrthurey/MuspelheimLauncher"
supportLink = "https://discord.gg/h8cRxgYX44"

[ejs.welcome]
welcomeHeader = "WELCOME TO MUSPELHEIM"
welcomeDescription = "You are using the Muspelheim Launcher, this launcher was made by Tyrthurey. A fork of CreateAcademyLauncher, which itself is a fork of HeliosLauncher. Muspelheim is a Minecraft server network that works together with many different modpacks. Team up with your friends, communicate seamlessly via the integrated voice chat, and engage in trade with other teams. So have a nice stay in Muspeleheim!"
welcomeDescCTA = "Come on! You are just a few clicks away from joining an awesome multi-modpack community!"
